branch-defaults:
  default:
    environment: Yelpcamp-prod
  deploy-to-aws:
    environment: Yelpcamp-prod
    group_suffix: null
  elastic-beanstalk-ready:
    environment: yelpcamp-prod
  splade-integration:
    environment: Yelpcamp-prod
environment-defaults:
  Yelpcamp-env:
    branch: null
    repository: null
  Yelpcamp-prod:
    branch: null
    repository: null
global:
  application_name: yelp-camp
  default_ec2_keyname: ec2
  default_platform: PHP 8.1 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
