branch-defaults:
  deploy-to-aws:
    environment: Yelpcamp-env
  splade-integration:
    environment: Yelpcamp-env

environment-defaults:
  Yelpcamp-env:
    branch: null
    repository: null
global:
  application_name: yelp-camp
  default_ec2_keyname: ec2
  default_platform: PHP 8.1 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
